### ISSUE TITLE
Reading all test files at startup takes several seconds

### ISSUE THREAD

**Issue by theseion** [coreruleset/go-ftw#115]
The function `GetTestsFromFiles` inf `files.go` takes several seconds to read all YAML test files into memory. While the number of tests has grown in recent weeks, the slowdown still feels significant.

**Comment by jcchavezs** [comment]
A few things to consider:
1. Do we load the files just once?
2. Is the yaml parser the most performant?
3. Is it possible to declare the yaml in go structs?
4. Shall we do lazy loading?

**Comment by anuraaga** [comment]
I suspect it's just I/O of 273 test files, ran `GetTestsFromFiles` and can confirm ~4s on my laptop, but in Coraza where we read the files in-memory after downloading, it's just 0.2s or so, CPU profile shows all time in YAML decode

https://github.com/corazawaf/coraza/blob/v3/dev/testing/coreruleset/coreruleset_test.go#L215

The only difference in implementation is `doublestar.GlobWalk` vs `filepathx.Glob`, but could confirm the latter is just ~3ms and is not the reason for the difference in time, so it seems the only difference can be in-memory vs file I/O.

**Comment by anuraaga** [comment]
Hmm but there indeed may have been a regression somewhere - when updating our build from 0.4.0 there is a several second pause at the beginning that wasn't there before

**Comment by anuraaga** [comment]
Yup sorry for the noise, could reproduce with in-memory too after updating to 0.4.2. Profile shows almost all the time in GC so something got much more allocation-heavy.

Also, I guess the release should have been 0.5, many behavior changes but also breaking API changes.

**Comment by anuraaga** [comment]
Bisected commits and confirmed that this introduced the performance problem

https://github.com/coreruleset/go-ftw/commit/39d90e3360bd78b702766a22445077e5976a84ad

The code looks fine so I guess it's because of the update of `goccy/go-yaml`.

**Comment by dune73** [comment]
Confirmed @anuraaga: Yes, I think it started with 0.4.0 here.

For the record: 8s to get going with the entire test tree.

**Comment by fzipi** [comment]
I can confirm this is a problem with the goccy/go-yaml update:
```
❯ time ./go-ftw check -d ../coreruleset/tests
ftw/check: checked 276 files, everything looks good!
./go-ftw check -d ../coreruleset/tests  32.94s user 2.53s system 376% cpu 9.430 total
❯ go get -u github.com/goccy/go-yaml@v1.8.10
go: downloading github.com/goccy/go-yaml v1.8.10
go: downloading golang.org/x/sys v0.2.0
go: downgraded github.com/goccy/go-yaml v1.9.6 => v1.8.10
go: upgraded golang.org/x/sys v0.1.0 => v0.2.0
❯ go build
❯ time ./go-ftw check -d ../coreruleset/tests
ftw/check: checked 276 files, everything looks good!
./go-ftw check -d ../coreruleset/tests  0.49s user 0.08s system 40% cpu 1.412 total
```
There are some features that we might use in the future with this library that the yaml v3 default don't have, so I will try to stick to this package initially.

Let's push a quick fix not downgrading it, and let's file a bug upstream.

**Comment by fzipi** [comment]
The problem is between v1.9.4 and v1.9.5:
```
ftw/check: checked 276 files, everything looks good!
./go-ftw check -d ../coreruleset/tests  0.51s user 0.09s system 100% cpu 0.595 total
❯ go get -u github.com/goccy/go-yaml@v1.9.5
go: downloading github.com/goccy/go-yaml v1.9.5
go: upgraded github.com/goccy/go-yaml v1.9.4 => v1.9.5
❯ go build
❯ time ./go-ftw check -d ../coreruleset/tests
ftw/check: checked 276 files, everything looks good!
./go-ftw check -d ../coreruleset/tests  32.93s user 2.49s system 346% cpu 10.221 total
```

**Comment by fzipi** [comment]
From https://github.com/goccy/go-yaml/compare/v1.9.2...v1.9.3, looks like the new node walking feature might be the big change.
