### ISSUE TITLE
About 411 Length Required response

### ISSUE THREAD

**Issue by camelmasa** [coreruleset/go-ftw#134]
CRS 942101-* tests received "411 Length Required" data. go-ftw sends `Content-Length` header if request data is not 0 byte for now.
https://github.com/coreruleset/go-ftw/blob/main/ftwhttp/header.go#L78-L80

I think the `Content-Length` header needed if request header's method is "POST".

Like this.
https://github.com/coreruleset/go-ftw/commit/04ec4209aef484f060b4edbd3ee6312240b9d0a7#diff-2c39b9ef80e191a7385eb8d54e378f12a1ee08e30e6682274902b68deb46bbbdR112-R114

If possible, Could we create a PR for this?

---

.ftw.yaml
```
testoverride:
  input:
    protocol: "https"
    dest_addr: "oursite.com"
    port: 443
mode: "cloud"
```

Also, Following is our command log.

```
go-ftw  run -t -d coreruleset/tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/ -i 942101 --connect-timeout 10s --trace
```

```
running 942101-6: 11:01AM DBG ftw/http: sending data:
POST /unittests@coreruleset.org"%20sleep(10.to_i)%20" HTTP/1.0
Connection: close
Host: oursite.com



11:01AM TRC ftw/http: sending data
11:01AM TRC ftw/http: receiving data
11:01AM TRC ftw/http: received data - "HTTP/1.0 411 Length Required\r\nContent-Type: text/html; charset=UTF-8\r\nReferrer-Policy: no-referrer\r\nContent-Length: 286\r\nDate: Sun, 26 Feb 2023 02:01:21 GMT\r\n\r\n\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>411 Length Required</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Length Required</h1>\n<h2>POST requests require a <code>Content-length</code> header.</h2>\n<h2></h2>\n</body></html>\n"
💥 failed in 146.461167ms (RTT 158.922959ms)
```

**Comment by theseion** [comment]
I agree, the `Content-Length` headers should be present even when the payload is empty. What server is responding to that request? Both httpd and nginx are fine without the header.

**Comment by camelmasa** [comment]
Thanks for a comment.

> What server is responding to that request?

We use GCP Load Balancer and Cloud Armor. Also, We enabled `evaluatePreconfiguredWaf('sqli-v33-stable', {'sensitivity': 4})`. This param can prevent CRS v3.3 SQL injection.
https://cloud.google.com/armor/docs/waf-rules?hl=en#sql_injection_sqli

**Comment by camelmasa** [comment]
I created a PR for this issue.
https://github.com/coreruleset/go-ftw/pull/135

**Comment by theseion** [comment]
Thanks for the info. You beat me to the PR :)

**Comment by jcchavezs** [comment]
Ping @M4tteoP
