### ISSUE TITLE
response_contains does not check the full response

### ISSUE THREAD

**Issue by snake66** [coreruleset/go-ftw#138]
The [ftw YAML format spec](https://github.com/coreruleset/ftw/blob/main/docs/YAMLFormat.md#response_contains) says:

> ### response_contains
>
> **Description:** Checks the entire response against the regular expression provided.

However, `go-ftw` only matches against the body of the response. This causes problems for tests that want to check that a a specific header is set by the firewall, or want to check responses that have no body.

**Comment by theseion** [comment]
Thanks for bringing this up. They way to go would be to add something like `header_contains`, and, possibly, `response_is_empty`.

**Comment by fzipi** [comment]
Well, reading it again, it is kind of ambiguous.

**Comment by snake66** [comment]
What is ambiguous? The existing spec? I think "the entire response" is quite precise.

**Comment by fzipi** [comment]
Yeah, but it is too broad. Anyway, let's make it work first.

**Comment by fzipi** [comment]
This was addressed already in 623805c62963431a23922675eedf524abd449ff6
