### ISSUE TITLE
Allow to wait for host to be ready 

### ISSUE THREAD

**Issue by jcchavezs** [coreruleset/go-ftw#142]
In many cases, more so when in a proxy, we need to wait and block until the proxy (using the WAF) is ready to accept requests.

The way we solved this in coraza-proxy-wasm is that we have a dedicated instruction running a curl and waiting for the host to be available. This is handy but not ideal as we have another piece of complexity for such a simple problem. Also in corporate envs, pulling an image isn't trivial and that is a friction.

I wish go-ftw allows to pass in a URL and it would wait until that URL returns 200.

**Comment by jcchavezs** [comment]
Any input on this @fzipi ?

**Comment by fzipi** [comment]
I don't think this makes sense. You mean the first time, in general, or what? This can be solved outside the tool, right?

**Comment by fzipi** [comment]
Let me see if I get this clear:
- there is a composer (or similar mechanism) that starts the waf and something else.
- that something else takes (some) time to be up and ready.
- the waf will answer some code, while that other container is not ready, that is NOT 200 OK.
- what is expected if there is an error and the upstream never is ready?

**Comment by jcchavezs** [comment]
If the upstream never gets ready it is pointless to run ftw so we just fail.
