### ISSUE TITLE
Regression test loading broken in 1.0.0

### ISSUE THREAD

**Issue by cbosss** [coreruleset/go-ftw#309]
Hey folks, 

v1.0.0 of this lib includes the following change from https://github.com/coreruleset/ftw-tests-schema:

https://github.com/coreruleset/ftw-tests-schema/commit/10f87b07f2d6bb093eba40bb65decbf74807d5c4

This commit changes how stages are parsed:

https://github.com/coreruleset/ftw-tests-schema/commit/10f87b07f2d6bb093eba40bb65decbf74807d5c4#diff-f8d2bd35e1a8c9b86c8c4448dde00bc5480652f85ed0630efc012c3906d3a14fL113-L117

I believe this is incompatible with how regression tests are defined in the coreruleset, ex: 

https://github.com/coreruleset/coreruleset/blob/v4.3.0/tests/regression/tests/REQUEST-911-METHOD-ENFORCEMENT/911100.yaml

When trying to parse these tests, the `Input` field is blank for all tests, due to the legacy nesting (`- stage:`). I'm wondering if this was an oversight, or if this lib doesn't try to maintain compatibility with those regression tests.

**Comment by theseion** [comment]
That is correct. We still use v0.6.4 of go-ftw for running tests. Migration to the updated format is currently in progress.
