### ISSUE TITLE
tests and runner is broken on windows

### ISSUE THREAD

**Issue by jabdr** [coreruleset/go-ftw#349]
### Description

go-ftw does not handle files descriptors properly and is therefore not able to run on windows. Windows refuses to delete files as long as a file descriptor is open.

I understand that windows is not officially supported, but I would like to contribute a few patches to improve the situation.

### PR

I created a pull request that fixes all issues that I could find on my windows system. With this patch I was then able to test coraza (after some patches) on windows.

https://github.com/coreruleset/go-ftw/pull/348

**Comment by fzipi** [comment]
We can probably add windows runners on this pipeline.

**Comment by jabdr** [comment]
@fzipi  I created a seperate branch with the worker matrix. Or would you rather have it with the first PR?

**Comment by fzipi** [comment]
No, it's totally fine to be in different PRs. 😄
