### ISSUE TITLE
Move to standard interfaces

### ISSUE THREAD

**Issue by fzipi** [coreruleset/go-ftw#38]
Initial implementation specifically went around standard interfaces like `Client` or `RoundTripper`.

Now that the project is working properly, we should revisit using standard interfaces to enable extensions from other users.

- [ ] Use net/http#Client in http/client.go
- [x] Review RoundTripper and move round trip times there

**Comment by fzipi** [comment]
Moved http to ftwhttp to simplify interfaces naming in the future.

**Comment by theseion** [comment]
I think we can close this. @fzipi?

**Comment by fzipi** [comment]
We can and we should.
