### ISSUE TITLE
ignore/forcefail/forcepass as regexes

### ISSUE THREAD

**Issue by M4tteoP** [coreruleset/go-ftw#75]
Hello,
I was wondering if it could be helpful to provide to the `testoverride` lists (`ignore`, `forcefail` and `forcepass`) a regex syntax like the `-i`/`-e` commands. The use case comes from a willingness to exclude all the tests of some specific rules (or even a specific file?) and, currently, the only way I see is listing individually all the tests in a quite verbose way.

Before:
```
...
testoverride:
  ignore:
  '932140-1': 'Currently excluding rule 932140'
  '932140-2': 'Currently excluding rule 932140'
  '932140-4': 'Currently excluding rule 932140'
  '932140-5': 'Currently excluding rule 932140'
  '932140-6': 'Currently excluding rule 932140'
  '932140-7': 'Currently excluding rule 932140'
  '932140-8': 'Currently excluding rule 932140'
  '932140-9': 'Currently excluding rule 932140'
  '932140-10': 'Currently excluding rule 932140'
  '932140-11': 'Currently excluding rule 932140'
  ...
```
After:
```
...
testoverride:
  ignore:
  '932140-*': 'Currently excluding rule 932140'
```

My concern is about the implementation: the check would become not just looking for the a value inside the map (e.g. [ignore](https://github.com/fzipi/go-ftw/blob/main/check/base.go#L63)), but iterating over a list of regex looking for a match. Do you think it's worth the overhead?

Thanks for the feedbacks!

**Comment by theseion** [comment]
That's a great idea. Concerning implementation, I don't think performance would suffer much since the amount of data to  match is pretty short, as is would the regular expression.

**Comment by fzipi** [comment]
It is a good idea, indeed. Let's add it to our backlog.

**Comment by M4tteoP** [comment]
Hi, I wrote some (most likely dumb) code: [Draft PR #80 ](https://github.com/fzipi/go-ftw/pull/80).
My concerns are about the change of the basic behaviour of simple rules.
A super trivial ignore of a single rule:
```
  ignore:
  '932140-1': 'Currently excluding rule 932140'
```
Now that becomes a regex leads to also remove rules like `932140-1`, `932140-10`, `932140-11`.
The rule should now become at least `'932140-1$'`, asserting the position at the end of the line. I feel it is a bit misleading if you face for the first time this functionality.

Thoughts about it? Could it be better to add other lists (something like `ignorePattern` or `ignoreRegex`) for this functionality?
```
...
testoverride:
  ignore:
    '932140-1': 'Currently excluding a specific test'
  ignorePattern:
    '932150-*': 'Currently excluding all the tests of a rule'
```

**Comment by M4tteoP** [comment]
Hi there, I implemented it in a bit better way (at least avoiding regex generation inside loops 😅) and added a bit of documentation about it. I removed the draft status from the [PR](https://github.com/coreruleset/go-ftw/pull/80), open to any advice about better implementing it!
Thanks :)
